name: Build and deploy ASP.NET Core app to Azure Web App - newsappbackend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/main_newsappbackend.yml'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_FILE: ./backend/NewsArticles/NewsArticles/NewsArticles.csproj
  PUBLISH_DIR:  ./publish
  WEBAPP_NAME:  newsappbackend

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_FILE }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_FILE }}" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_FILE }}" -c Release -o "${{ env.PUBLISH_DIR }}"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-publish
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-publish
          path: ./artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6EDC9825C8634E0EB8CB447D7CA98B63 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7D5DF72C816F4EDBB7636160A44E6CBA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D529BE6FC5B5449B912484099D8B5471 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name:  ${{ env.WEBAPP_NAME }}
          slot-name: Production
          package:   ./artifact

